number = int(input())
def multiplitaionTable(number):
  print(f'1 x {number} = {number*1}')
  print(f'2 x {number} = {number*2}')
  print(f'3 x {number} = {number*3}')
  print(f'4 x {number} = {number*4}')
  print(f'5 x {number} = {number*5}')
  print(f'6 x {number} = {number*6}')
  print(f'7 x {number} = {number*7}')
  print(f'8 x {number} = {number*8}')
  print(f'9 x {number} = {number*9}')
  print(f'10 x {number} = {number*10}')
multiplitaionTable(number)